from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    ListFlowable,
    ListItem
)


def generate_project_report(data):
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=50,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=26,
        textColor=colors.HexColor("#4338CA"),
        spaceAfter=20,
        alignment=1
    )

    section_style = ParagraphStyle(
        "SectionStyle",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=15,
        textColor=colors.HexColor("#2563EB"),
        spaceBefore=16,
        spaceAfter=10
    )

    normal_style = ParagraphStyle(
        "NormalStyle",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=10.5,
        leading=16,
        textColor=colors.HexColor("#111827"),
        spaceAfter=8
    )

    small_style = ParagraphStyle(
        "SmallStyle",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#374151")
    )

    story = []

    story.append(Paragraph("AgentFlowAI Project Analysis Report", title_style))
    story.append(Paragraph("AI-Powered Requirement Engineering Report", normal_style))
    story.append(Spacer(1, 15))

    project_idea = data.get("project_idea", "Not provided")
    domain = data.get("domain", "Not classified")
    questions = data.get("questions", [])
    tech_stack = data.get("tech_stack", "Not generated")
    feasibility = data.get("feasibility", "Not generated")
    feedback = data.get("feedback", "No feedback submitted")

    overview_data = [
        ["Project Idea", project_idea],
        ["Detected Domain", domain],
        ["Generated By", "AgentFlowAI"],
    ]

    overview_table = Table(
        overview_data,
        colWidths=[1.7 * inch, 4.8 * inch]
    )

    overview_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#EEF2FF")),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#3730A3")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))

    story.append(overview_table)

    story.append(Paragraph("Requirement Gathering Questions", section_style))

    if questions:
        question_items = []

        for question in questions:
            clean_question = str(question).strip()

            if clean_question:
                question_items.append(
                    ListItem(
                        Paragraph(clean_question, normal_style),
                        bulletColor=colors.HexColor("#4F46E5")
                    )
                )

        story.append(
            ListFlowable(
                question_items,
                bulletType="bullet",
                leftIndent=20
            )
        )
    else:
        story.append(Paragraph("No questions generated.", normal_style))

    story.append(Paragraph("Recommended Tech Stack", section_style))
    story.append(Paragraph(tech_stack.replace("\n", "<br/>"), normal_style))

    story.append(Paragraph("Feasibility Analysis", section_style))
    story.append(Paragraph(feasibility.replace("\n", "<br/>"), normal_style))

    story.append(Paragraph("User Feedback / Answers", section_style))
    story.append(Paragraph(feedback.replace("\n", "<br/>"), normal_style))

    story.append(Spacer(1, 20))

    story.append(Paragraph(
        "This report was generated automatically by AgentFlowAI to support early-stage software requirement analysis, feasibility understanding, and project planning.",
        small_style
    ))

    def add_footer(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#6B7280"))
        canvas.drawString(40, 25, "AgentFlowAI - AI Requirement Engineering Platform")
        canvas.drawRightString(555, 25, f"Page {doc.page}")
        canvas.restoreState()

    doc.build(
        story,
        onFirstPage=add_footer,
        onLaterPages=add_footer
    )

    buffer.seek(0)
    return buffer